version: "3.1"

services:
  dask-sql:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        release: "3.10.0-bullseye"
        REBUILD_VER: "date"
    image: dsql/dsqlconda:local
    command: ["dask-scheduler"]

